name: build levhttpd Android ARMv7

on:
  workflow_dispatch:
  push:

jobs:
  build:
    name: Android ARMv7 (armeabi-v7a)
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26d

      - name: Build levhttpd for Android ARMv7
        run: |
          export T=$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin

          $T/armv7a-linux-androideabi21-clang \
            -O2 \
            -fPIE \
            -pie \
            levhttpd.c \
            -o levhttpd-android-armv7

          $T/llvm-strip levhttpd-android-armv7

          file levhttpd-android-armv7

      - uses: actions/upload-artifact@v4
        with:
          name: levhttpd-android-armv7
          path: levhttpd-android-armv7
