name: build uhttpd

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26d

      - name: build
        run: |
          export T=$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin

          $T/armv7a-linux-androideabi21-clang \
            -O2 \
            -fPIE \
            -pie \
            uhttpd.c \
            -o uhttpd

          $T/llvm-strip uhttpd

      - uses: actions/upload-artifact@v4
        with:
          name: uhttpd-armv7
          path: uhttpd
